# Jekyll datas
exclude: ['_site', '.idea']
source: src

# Other global variables:
test : test
algorithms:
 -  name: Méthodes des K plus proches voisins
    href: KNN
    picture: /static/img/KNN.svg
    icon: <i class="far fa-dot-circle"></i>
    currentVersion: 1.0
    missionDescription: Cette mission consiste à déterminer le type d'une certaine fleur en comptant la majorité parmis les K fleurs les plus proches.
    kindOfMethod: Méthode de classification
    shortDescription: >
      A partir d'une entrée x on déterminera sa classe à partir de ses K voisins les plus proches.
      Après cela avec l'information de la classe réelle de l'entrée, nous serons en mesure d'évaluer l'exactitude de notre classifieur.
    sections:
      activityName: Blockly
 -  name: Arbre de décisions
    href: arbre
    picture: /static/img/ArbreDecision.svg
    icon: <i class="fas fa-tree"></i>
    currentVersion: 1.0
    missionDescription: Cette mission interactive consiste à déterminer un certain objet en créant manuellement un arbre de décision pertinent.
    kindOfMethod: Méthode de classification
    shortDescription: >
      Outil d'aide à la décision représentant un ensemble de choix sous la forme graphique d'un arbre.
      Les différentes décisions possibles sont situées aux extrémités des branches (les « feuilles » de l'arbre), et sont atteints en fonction de décisions prises à chaque étape.
    sections:
      activityName: Arbre interactif
 - name: Réseau neuronal
   href: NN
   picture: /static/img/NN.svg
   icon: <svg class="icon icon-cart" role="img" xmlns="http://www.w3.org/2000/svg" style="height:21px" viewBox="0 0 640 512" class="svg-inline--fa fa-chart-network fa-w-20"><path fill="currentColor" d="M568 368c-19.1 0-36.3 7.6-49.2 19.7L440.6 343c4.5-12.2 7.4-25.2 7.4-39 0-61.9-50.1-112-112-112-8.4 0-16.6 1.1-24.4 2.9l-32.2-69c15-13.2 24.6-32.3 24.6-53.8 0-39.8-32.2-72-72-72s-72 32.2-72 72 32.2 72 72 72c.9 0 1.8-.2 2.7-.3l33.5 71.7C241.5 235.9 224 267.8 224 304c0 61.9 50.1 112 112 112 30.7 0 58.6-12.4 78.8-32.5l82.2 47c-.4 3.1-1 6.3-1 9.5 0 39.8 32.2 72 72 72s72-32.2 72-72-32.2-72-72-72zM232 96c-13.2 0-24-10.8-24-24s10.8-24 24-24 24 10.8 24 24-10.8 24-24 24zm104 272c-35.3 0-64-28.7-64-64s28.7-64 64-64 64 28.7 64 64-28.7 64-64 64zm232 96c-13.2 0-24-10.8-24-24s10.8-24 24-24 24 10.8 24 24-10.8 24-24 24zm-54.4-261.2l-19.2-25.6-48 36 19.2 25.6 48-36zM576 192c35.3 0 64-28.7 64-64s-28.7-64-64-64-64 28.7-64 64 28.7 64 64 64zM152 320h48v-32h-48v32zm-88-80c-35.3 0-64 28.7-64 64s28.7 64 64 64 64-28.7 64-64-28.7-64-64-64z" class="" data-darkreader-inline-fill="" style="--darkreader-inline-fill:currentColor;"></path></svg>
   currentVersion: 1.0
   missionDescription: Cette mission consiste à utiliser un réseau de neuronne existant afin de reconnaitre un certain chiffre.
   kindOfMethod: Méthode de classification
   shortDescription: >
     TODO
   sections:
     activityName: Réseau de neurone interactif